# A Quick Introduction of Python


This is only ment as a brief intorduction of the basics of coding in python an dis by no means a comprehensive overview of its capabilities.


## Data Types

There are 4 basic data types: 1) integers referred to as `int`, 2) decimal numbers referred to as `float`,3) charater strings referred to as `str`, and 4) boolean values referred to as `bool`.

In [6]:
number = 3.2
number, type(number)


(3.2, float)

In [7]:

number = int(number)
number, type(number)


('3', str)

In [ ]:

number = str(number)
number, type(number)

In [9]:
var = True
var, type(var)

(True, bool)

## Data Types
Integers, floating point numbers, and character strings can be organised into different structures: `list`, `dict`,`tuples`

In [8]:
# Lists
list_1 = list((1,2,3,4,5))
list_2 = ["apple", "banana", 35.248, 150]
list_3 = ["apple", "banana", 150, "apple", 150]


[1, 2, 3, 4, 5]

In [14]:
# dictionaries
first_dict = dict(name = "John", age = 36, country = "Norway")
first_dict

{'name': 'John', 'age': 36, 'country': 'Norway'}

In [13]:
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
thisdict

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964}

In [16]:
# Tuples
mytuple = ("apple", "banana", "cherry")
len(mytuple)

3

## Indexing in python
In Python, indexing starts from 0, which means the first element in a sequence is at position 0, the second element is at position 1, and so on.

In [18]:
a = ['spam', 'egg', 'bacon', 'tomato', 'ham', 'lobster']
a

['spam', 'egg', 'bacon', 'tomato', 'ham', 'lobster']

 Lists elements can be accessed using a numerical index in square brackets:

In [19]:
a[0]

'spam'

In [ ]:
# Select the 3rd element in the list

List elements can also be accessed using a negative list index, which counts from the end of the list:

In [20]:
a[-1]

'lobster'

In [ ]:
# Select the second to last element in the list a

## Arrays
Arrays are a fundamental data structure, and an important part of most programming languages. In Python, they are containers which are able to store more than one item at the same time.

The main difference between lists and arrays is that lists can store various data types. This means that a list can contain integers, floating point numbers, strings, or any other Python data type, at the same time. That is not the case with arrays.

As mentioned in the section above, arrays store only items that are of the same single data type. There are arrays that contain only integers, or only floating point numbers, or only any other Python data type you want to use.

Source: https://www.freecodecamp.org/news/python-array-tutorial-define-index-methods/

### NumPy Arrays
The numpy library is commonly uses for arrays.

NumPy (Numerical Python) is an open source Python library that’s used in almost every field of science and engineering. It’s the universal standard for working with numerical data in Python, and it’s at the core of the scientific Python and PyData ecosystems.

The NumPy library contains multidimensional array and matrix data structures. It provides ndarray, a homogeneous n-dimensional array object, with methods to efficiently operate on it.
Source: https://numpy.org/doc/stable/user/absolute_beginners.html

In [21]:
import numpy as np

In [24]:
a = np.arange(5)
a, type(a), a.shape

(array([0, 1, 2, 3, 4]), numpy.ndarray, (5,))

In [25]:
a2 = a[np.newaxis, :]
a2.shape

(1, 5)

In [28]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
#a.shape
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [29]:
a.sum()

78

Lets see if this works on a list!?!

In [30]:
b = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
b.sum()

AttributeError: 'list' object has no attribute 'sum'

## Indexing in a NumPy array

In [32]:
a = np.arange(100).reshape(10,10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [33]:
# a[0,:] is the same as a[0]
a[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
a[:,0]

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [35]:
a[3,5]

35

In [ ]:
# which number is in the fifth row, seventh column?

In [38]:
b = np.arange(24).reshape((4,2,3))
b

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]]])

In [40]:
c = np.arange(96).reshape(4,4,2,3)
c

array([[[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23]]],


       [[[24, 25, 26],
         [27, 28, 29]],

        [[30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41]],

        [[42, 43, 44],
         [45, 46, 47]]],


       [[[48, 49, 50],
         [51, 52, 53]],

        [[54, 55, 56],
         [57, 58, 59]],

        [[60, 61, 62],
         [63, 64, 65]],

        [[66, 67, 68],
         [69, 70, 71]]],


       [[[72, 73, 74],
         [75, 76, 77]],

        [[78, 79, 80],
         [81, 82, 83]],

        [[84, 85, 86],
         [87, 88, 89]],

        [[90, 91, 92],
         [93, 94, 95]]]])

In [41]:
b = np.arange(24).reshape((4,2,3))
b[0,:,:] = 1
b

array([[[ 1,  1,  1],
        [ 1,  1,  1]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]]])

In [42]:
b = np.arange(24).reshape((4,2,3))
b[0,:,:] = b[0,:,:] + 1
b

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]]])